open_collective: joda
tidelift: maven/joda-time:joda-time

# github: [jodastephen]
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with a single custom sponsorship URL
