name: Release

on:
  push:
    tags:
      - 'release*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: -e -B -ntp -DtrimStackTrace=false

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
      with:
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        ref: "main"
        fetch-tags: true

    - name: Setup git
      run: |
        git config --global user.name "Stephen Colebourne (CI)"
        git config --global user.email "scolebourne@joda.org"

    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  #v4.7.0
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo "--settings" >> ./.mvn/maven.config
        echo "$( pwd )/.github/maven-settings.xml" >> ./.mvn/maven.config
        mvn --version
        mkdir -p target

    #------------------------------------------------------------------------
    - name: Maven release
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      run: |
        mvn clean deploy -Doss.repo

    - name: Update website
      run: |
        git tag websiterelease
        git push origin websiterelease

    - name: Delete release tag
      if: "always()"
      run: |
        git tag --delete "${GITHUB_REF_NAME}" || true
        git push --delete origin "${GITHUB_REF_NAME}" || true
